"""generate_application_pack_deploy_commands — emit runnable deploy scripts.

Writes profile-specific deployment command scripts into a standalone App Pack
bundle so teams can deploy without AAF runtime dependencies.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
import re
from typing import Any

_PROFILE_RE = re.compile(r"^[a-z][a-z0-9-]{0,31}$")


def _safe_profile(profile: str) -> str:
    candidate = (profile or "").strip().lower()
    if not candidate:
        raise ValueError("profile is required.")
    if not _PROFILE_RE.fullmatch(candidate):
        raise ValueError(f"Invalid profile: '{candidate}'")
    return candidate


def _safe_bundle_path(bundle_path: str) -> Path:
    candidate = (bundle_path or "").strip()
    if not candidate:
        raise ValueError("bundle_path is required.")

    path = Path(candidate).resolve()
    if not path.exists() or not path.is_dir():
        raise ValueError(f"Bundle path does not exist: {path}")
    return path


def _ps_escape(value: str) -> str:
    return value.replace("'", "''")


def _sh_escape(value: str) -> str:
    return value.replace("'", "'\"'\"'")


def _render_powershell(profile: str, deployment_name: str, location: str) -> str:
    return "\n".join([
        "Param(",
        "    [Parameter(Mandatory=$false)][string]$SubscriptionId = '',",
        "    [Parameter(Mandatory=$false)][string]$ResourceGroup = '',",
        f"    [Parameter(Mandatory=$false)][string]$Location = '{_ps_escape(location)}'",
        ")",
        "",
        "$ErrorActionPreference = 'Stop'",
        "$ScriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path",
        "$BundleRoot = Resolve-Path (Join-Path $ScriptRoot '..\\..')",
        "$TemplateFile = Join-Path $BundleRoot 'infra\\main.bicep'",
        f"$ParametersFile = Join-Path $BundleRoot 'deploy\\parameters\\deployment-parameters.{_ps_escape(profile)}.json'",
        "",
        "if (-not (Test-Path $TemplateFile)) { throw \"Template file not found: $TemplateFile\" }",
        "if (-not (Test-Path $ParametersFile)) { throw \"Parameters file not found: $ParametersFile\" }",
        "if ([string]::IsNullOrWhiteSpace($ResourceGroup)) { throw 'ResourceGroup is required.' }",
        "",
        "if (-not [string]::IsNullOrWhiteSpace($SubscriptionId)) {",
        "    az account set --subscription $SubscriptionId | Out-Null",
        "}",
        "",
        "if ([string]::IsNullOrWhiteSpace($Location)) {",
        "    $Location = (az group show -n $ResourceGroup --query location -o tsv)",
        "}",
        "",
        "az group create --name $ResourceGroup --location $Location | Out-Null",
        f"az deployment group create --resource-group $ResourceGroup --name '{_ps_escape(deployment_name)}' --template-file $TemplateFile --parameters @$ParametersFile",
        "",
        "Write-Host 'Deployment command completed.'",
        "",
        f"# Generated by AAF at {datetime.now().isoformat()}",
    ])


def _render_bash(profile: str, deployment_name: str, location: str) -> str:
    return "\n".join([
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        "SUBSCRIPTION_ID=\"${SUBSCRIPTION_ID:-}\"",
        "RESOURCE_GROUP=\"${RESOURCE_GROUP:-}\"",
        f"LOCATION=\"${{LOCATION:-{_sh_escape(location)}}}\"",
        "",
        "SCRIPT_DIR=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")\" && pwd)\"",
        "BUNDLE_ROOT=\"$(cd \"${SCRIPT_DIR}/../..\" && pwd)\"",
        "TEMPLATE_FILE=\"${BUNDLE_ROOT}/infra/main.bicep\"",
        f"PARAMETERS_FILE=\"${{BUNDLE_ROOT}}/deploy/parameters/deployment-parameters.{_sh_escape(profile)}.json\"",
        "",
        "if [[ ! -f \"${TEMPLATE_FILE}\" ]]; then",
        "  echo \"Template file not found: ${TEMPLATE_FILE}\" >&2",
        "  exit 1",
        "fi",
        "if [[ ! -f \"${PARAMETERS_FILE}\" ]]; then",
        "  echo \"Parameters file not found: ${PARAMETERS_FILE}\" >&2",
        "  exit 1",
        "fi",
        "if [[ -z \"${RESOURCE_GROUP}\" ]]; then",
        "  echo \"RESOURCE_GROUP is required.\" >&2",
        "  exit 1",
        "fi",
        "",
        "if [[ -n \"${SUBSCRIPTION_ID}\" ]]; then",
        "  az account set --subscription \"${SUBSCRIPTION_ID}\" >/dev/null",
        "fi",
        "",
        "az group create --name \"${RESOURCE_GROUP}\" --location \"${LOCATION}\" >/dev/null",
        f"az deployment group create --resource-group \"${{RESOURCE_GROUP}}\" --name '{_sh_escape(deployment_name)}' --template-file \"${{TEMPLATE_FILE}}\" --parameters @\"${{PARAMETERS_FILE}}\"",
        "",
        "echo \"Deployment command completed.\"",
        "",
        f"# Generated by AAF at {datetime.now().isoformat()}",
    ])


def generate_application_pack_deploy_commands(
    bundle_path: str,
    profile: str = "dev",
    deployment_name: str = "aaf-app-pack-deployment",
    location: str = "eastus",
) -> dict[str, Any]:
    """Generate deploy scripts for an exported app pack bundle.

    Parameters
    ----------
    bundle_path:
        Absolute path to an exported app pack bundle.
    profile:
        Deployment profile matching generated parameter files (dev/test/prod).
    deployment_name:
        ARM deployment name used in ``az deployment group create``.
    location:
        Default Azure region used when creating the resource group.

    Returns
    -------
    dict
        Status and generated script file paths.
    """
    try:
        bundle_dir = _safe_bundle_path(bundle_path)
        profile = _safe_profile(profile)
    except ValueError as exc:
        return {"error": str(exc)}

    parameters_file = bundle_dir / "deploy" / "parameters" / f"deployment-parameters.{profile}.json"
    if not parameters_file.exists():
        return {
            "error": (
                f"Parameter file not found for profile '{profile}'. "
                f"Expected: {parameters_file}"
            )
        }

    commands_dir = bundle_dir / "deploy" / "commands"
    commands_dir.mkdir(parents=True, exist_ok=True)

    ps1_path = commands_dir / f"deploy-{profile}.ps1"
    sh_path = commands_dir / f"deploy-{profile}.sh"

    ps1_path.write_text(
        _render_powershell(profile=profile, deployment_name=deployment_name, location=location),
        encoding="utf-8",
    )
    sh_path.write_text(
        _render_bash(profile=profile, deployment_name=deployment_name, location=location),
        encoding="utf-8",
    )

    try:
        sh_path.chmod(0o755)
    except OSError:
        pass

    return {
        "status": "generated",
        "bundlePath": str(bundle_dir),
        "profile": profile,
        "deploymentName": deployment_name,
        "files": {
            "powershell": str(ps1_path),
            "bash": str(sh_path),
        },
    }
