apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: api-gateway
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: REPLACE_WITH_ACR/api-gateway:dev
  - target:
      kind: Deployment
      name: catalog-service
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: REPLACE_WITH_ACR/catalog-service:dev
  - target:
      kind: Deployment
      name: order-service
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: REPLACE_WITH_ACR/order-service:dev
  - target:
      kind: Deployment
      name: payment-service
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: REPLACE_WITH_ACR/payment-service:dev
