apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aks-micro-demo
resources:
  - namespace.yaml
  - configmap.yaml
  - catalog.yaml
  - order.yaml
  - payment.yaml
  - api-gateway.yaml
  - ingress.yaml
  - hpa.yaml
