using '../main.bicep'

param baseName = 'casewright'
param environmentName = 'legal-dev-us'
param location = 'eastus'
param searchLocation = 'eastus'
param apiImage = 'mcr.microsoft.com/azuredocs/containerapps-helloworld:latest'
param workerImage = 'mcr.microsoft.com/azuredocs/containerapps-helloworld:latest'
param graphTenantId = ''
param graphClientId = ''
param sharePointSyncSchedule = '0 0 */6 * * *'
param syncDefaultTenantId = ''
param embeddingDimensions = 3072
param foundryAgentId = ''

// Generated by AAF Application Zone at 2026-06-30T12:58:16.593071