Param(
    [Parameter(Mandatory=$false)][string]$SubscriptionId = '',
    [Parameter(Mandatory=$false)][string]$ResourceGroup = '',
    [Parameter(Mandatory=$false)][string]$Location = 'eastus'
)

$ErrorActionPreference = 'Stop'
$ScriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$BundleRoot = Resolve-Path (Join-Path $ScriptRoot '..\..')
$TemplateFile = Join-Path $BundleRoot 'infra\main.bicep'
$ParametersFile = Join-Path $BundleRoot 'deploy\parameters\deployment-parameters.dev.json'

if (-not (Test-Path $TemplateFile)) { throw "Template file not found: $TemplateFile" }
if (-not (Test-Path $ParametersFile)) { throw "Parameters file not found: $ParametersFile" }
if ([string]::IsNullOrWhiteSpace($ResourceGroup)) { throw 'ResourceGroup is required.' }

if (-not [string]::IsNullOrWhiteSpace($SubscriptionId)) {
    az account set --subscription $SubscriptionId | Out-Null
}

if ([string]::IsNullOrWhiteSpace($Location)) {
    $Location = (az group show -n $ResourceGroup --query location -o tsv)
}

az group create --name $ResourceGroup --location $Location | Out-Null
az deployment group create --resource-group $ResourceGroup --name 'casewright-dev' --template-file $TemplateFile --parameters @$ParametersFile

Write-Host 'Deployment command completed.'

# Generated by AAF at 2026-06-30T13:03:36.172663