#!/usr/bin/env bash
set -euo pipefail

SUBSCRIPTION_ID="${SUBSCRIPTION_ID:-}"
RESOURCE_GROUP="${RESOURCE_GROUP:-}"
LOCATION="${LOCATION:-eastus}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUNDLE_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
TEMPLATE_FILE="${BUNDLE_ROOT}/infra/main.bicep"
PARAMETERS_FILE="${BUNDLE_ROOT}/deploy/parameters/deployment-parameters.dev.json"

if [[ ! -f "${TEMPLATE_FILE}" ]]; then
  echo "Template file not found: ${TEMPLATE_FILE}" >&2
  exit 1
fi
if [[ ! -f "${PARAMETERS_FILE}" ]]; then
  echo "Parameters file not found: ${PARAMETERS_FILE}" >&2
  exit 1
fi
if [[ -z "${RESOURCE_GROUP}" ]]; then
  echo "RESOURCE_GROUP is required." >&2
  exit 1
fi

if [[ -n "${SUBSCRIPTION_ID}" ]]; then
  az account set --subscription "${SUBSCRIPTION_ID}" >/dev/null
fi

az group create --name "${RESOURCE_GROUP}" --location "${LOCATION}" >/dev/null
az deployment group create --resource-group "${RESOURCE_GROUP}" --name 'casewright-dev' --template-file "${TEMPLATE_FILE}" --parameters @"${PARAMETERS_FILE}"

echo "Deployment command completed."

# Generated by AAF at 2026-06-30T13:03:36.178199